#!/bin/sh

index_file='index.html'
build_dir='build'
lang_dir='lang'

# source common file
set -a
. "${lang_dir}/.common"
set +a

for lang in `ls "$lang_dir"`; do

    mkdir -p "${build_dir}/${lang}"

    set -a
    . "${lang_dir}/${lang}"
    set +a

    envsubst < "$index_file" | tee "${build_dir}/${lang}/index_${lang}.html"

    # TODO find alternative to this
    cp 'index.css' "${build_dir}/${lang}/"
done

