#!/bin/sh

index_file='index.html'
build_dir='build'
lang_dir='lang'

# source common file
set -a
. "${lang_dir}/.common"
set +a

for lang in `ls "$lang_dir"`; do

    mkdir -p "${build_dir}"

    set -a
    . "${lang_dir}/${lang}"
    set +a

    envsubst < "$index_file" | tee "${build_dir}/index_${lang}.html"

done

# set default index page
default_lang='en'
cp "${build_dir}/index_${default_lang}.html" "${build_dir}/index.html"


# TODO find alternative to this
cp 'index.css' "${build_dir}"
